:Author: vansh3022
:Email:
:Date: 30/09/2021
:Revision: version#
:License: Public Domain

= Project: SIT210-Task5.1P-RPi - GPIO Basics

Blinking Led Project using Raspberry Pi

== Step 1: Installation
Connect the DHT22 sensor to the Nano 33 IoT according to the sketch uploaded on Arduino IOT Cloud and provide a network connection to show real-time changes in data on the dashboard 

For example:

1. Open this file
2. Refer to the Pictures for the connections
3. Build the dashboard taking reference of the Picture above  

== Step 2: Assemble the circuit

Assemble the circuit following the diagram layout.png attached to the sketch

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 Project: SIT210-Task5.1P-RPi - GPIO Basics       => Arduino sketch folder
  ├── sketch123.ino                               => main Arduino file
  ├── Dashboard.png                               => An image of the Dashboard
  ├── Layout.jfif                                 => An image of the circuit layout
  └── ReadMe.adoc                                 => Method to work with the files
....

=== License
This project is released under a Public License.

=== Contributing
To contribute to this project please contact: 9996250931 

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name          | Part number | Quantity
| U1 | Usb Cable          | UCX00066    | 1
| R1 | Raspberry Pi       | RPX00066    | 1
| B1 | Breadboard(any)    | BBX00066    | 1
| J1 | Jumper Wires       | JWX00066    | 5
| L1 | Led                | LEX00066    | 3
| R1 | Resistor           | REX00066    | 3
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents. 
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
